// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjmRGU773vSFrlV_ulllVYlOQ9myNlPMU',
    appId: '1:369409894769:web:b65213ce0fa15c7702eed0',
    messagingSenderId: '369409894769',
    projectId: 'anime-watchlist-app-dd654',
    authDomain: 'anime-watchlist-app-dd654.firebaseapp.com',
    storageBucket: 'anime-watchlist-app-dd654.appspot.com',
    measurementId: 'G-R6VJRRKNLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhYcdhlWprtan-v0WGeBAd8-v3CkRDMqo',
    appId: '1:369409894769:android:7c7c6409507e6b8002eed0',
    messagingSenderId: '369409894769',
    projectId: 'anime-watchlist-app-dd654',
    storageBucket: 'anime-watchlist-app-dd654.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZO2B-k2J66yAmt9DzWtfrfFOuDDhbn0k',
    appId: '1:369409894769:ios:8298d45131cd106902eed0',
    messagingSenderId: '369409894769',
    projectId: 'anime-watchlist-app-dd654',
    storageBucket: 'anime-watchlist-app-dd654.appspot.com',
    iosBundleId: 'com.example.animeWatchlistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZO2B-k2J66yAmt9DzWtfrfFOuDDhbn0k',
    appId: '1:369409894769:ios:67b4d000764015fa02eed0',
    messagingSenderId: '369409894769',
    projectId: 'anime-watchlist-app-dd654',
    storageBucket: 'anime-watchlist-app-dd654.appspot.com',
    iosBundleId: 'com.example.animeWatchlistApp.RunnerTests',
  );
}
